/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package motorph_sytaxsippers_ps;

import com.opencsv.exceptions.CsvException;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static motorph_sytaxsippers_ps.OpenCsv_UpdateData.updateCSV;

public class AdminUserInterface_UpdateEmp extends javax.swing.JFrame {

    /**
     * Creates new form AdminUserInterface_UpdateEmp
     */
    public AdminUserInterface_UpdateEmp(String empNumber, String empLastName, String empFirstName, String empSSS, String empPhilH, String empTIN, String empPAGIBIG) {
        initComponents();

        //empNumber, empLastName, empFirstName,empSSS,empPhilH,empTIN,empPAGIBIG
        jText_EmpNumber.setText(empNumber);
        jText_LatName.setText(empLastName);
        jText_Fname.setText(empFirstName);
        jText_SSS.setText(empSSS);
        jText_PhilHealth.setText(empPhilH);
        jText_TIN.setText(empTIN);
        jText_PAGIBIG.setText(empPAGIBIG);

    }

    
            public void close() {

        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLbl_EmpNo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLbl_Fname = new javax.swing.JLabel();
        jLbl_SSSnum = new javax.swing.JLabel();
        jLbl_PhilHealth = new javax.swing.JLabel();
        jLbl_TIN = new javax.swing.JLabel();
        jLbl_PagIbig = new javax.swing.JLabel();
        jText_EmpNumber = new javax.swing.JTextField();
        jText_LatName = new javax.swing.JTextField();
        jText_Fname = new javax.swing.JTextField();
        jText_SSS = new javax.swing.JTextField();
        jText_PhilHealth = new javax.swing.JTextField();
        jText_TIN = new javax.swing.JTextField();
        jText_PAGIBIG = new javax.swing.JTextField();
        jBtn_Update = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 80));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("UPDATE EMPLOYEE INFORMATION");

        jLbl_EmpNo.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLbl_EmpNo.setForeground(new java.awt.Color(255, 255, 255));
        jLbl_EmpNo.setText("EMPLOYEE NO:");

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("EMPLOYEE LAST NAME: ");

        jLbl_Fname.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLbl_Fname.setForeground(new java.awt.Color(255, 255, 255));
        jLbl_Fname.setText("EMPLOYEE FIRST NAME: ");

        jLbl_SSSnum.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLbl_SSSnum.setForeground(new java.awt.Color(255, 255, 255));
        jLbl_SSSnum.setText("SSS NUMBER:");

        jLbl_PhilHealth.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLbl_PhilHealth.setForeground(new java.awt.Color(255, 255, 255));
        jLbl_PhilHealth.setText("PHILHEALTH NUMBER:");

        jLbl_TIN.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLbl_TIN.setForeground(new java.awt.Color(255, 255, 255));
        jLbl_TIN.setText("TIN NUMBER:");

        jLbl_PagIbig.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLbl_PagIbig.setForeground(new java.awt.Color(255, 255, 255));
        jLbl_PagIbig.setText("PAGIBIG NUMBER:");

        jText_EmpNumber.setEditable(false);

        jText_Fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_FnameActionPerformed(evt);
            }
        });

        jText_PhilHealth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_PhilHealthActionPerformed(evt);
            }
        });

        jBtn_Update.setText("UPDATE");
        jBtn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_UpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jText_LatName, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLbl_PagIbig)
                                    .addComponent(jLbl_EmpNo)
                                    .addComponent(jLabel4)
                                    .addComponent(jLbl_Fname)
                                    .addComponent(jLbl_SSSnum)
                                    .addComponent(jLbl_PhilHealth)
                                    .addComponent(jLbl_TIN))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jText_EmpNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jText_Fname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jText_SSS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jText_PhilHealth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jText_TIN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jText_PAGIBIG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jBtn_Update)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_EmpNo)
                    .addComponent(jText_EmpNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jText_LatName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_Fname)
                    .addComponent(jText_Fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_SSSnum)
                    .addComponent(jText_SSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_PhilHealth)
                    .addComponent(jText_PhilHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_TIN)
                    .addComponent(jText_TIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_PagIbig)
                    .addComponent(jText_PAGIBIG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jBtn_Update)
                .addGap(40, 40, 40))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 480));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/bg4.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_UpdateActionPerformed

        String currentPath = System.getProperty("user.dir");
        String csvFile = currentPath + File.separator + "resources" + File.separator + "EmployeeDetails_AdminView.csv";

        String empNum = jText_EmpNumber.getText();
        String empLName = jText_LatName.getText();
        String empFName = jText_Fname.getText();
        String empSSSNo = jText_SSS.getText();
        String empPhilHNo = jText_PhilHealth.getText();
        String empTINNo = jText_TIN.getText();
        String empPAGIBIGNo = jText_PAGIBIG.getText();

        String empNumber = empNum; // Example employee number
        String[] updatedData = {empNum, empLName, empFName, empSSSNo, empPhilHNo, empTINNo, empPAGIBIGNo}; 
        
        try {
            updateCSV(csvFile, empNumber, updatedData);
            close();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (IllegalArgumentException e) {
            System.err.println(e.getMessage());
        } catch (CsvException ex) {
            Logger.getLogger(AdminUserInterface_UpdateEmp.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jBtn_UpdateActionPerformed

    private void jText_FnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_FnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_FnameActionPerformed

    private void jText_PhilHealthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_PhilHealthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_PhilHealthActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUserInterface_UpdateEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUserInterface_UpdateEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUserInterface_UpdateEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUserInterface_UpdateEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new AdminUserInterface_UpdateEmp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLbl_EmpNo;
    private javax.swing.JLabel jLbl_Fname;
    private javax.swing.JLabel jLbl_PagIbig;
    private javax.swing.JLabel jLbl_PhilHealth;
    private javax.swing.JLabel jLbl_SSSnum;
    private javax.swing.JLabel jLbl_TIN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jText_EmpNumber;
    private javax.swing.JTextField jText_Fname;
    private javax.swing.JTextField jText_LatName;
    private javax.swing.JTextField jText_PAGIBIG;
    private javax.swing.JTextField jText_PhilHealth;
    private javax.swing.JTextField jText_SSS;
    private javax.swing.JTextField jText_TIN;
    // End of variables declaration//GEN-END:variables
}
