/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package motorph_sytaxsippers_ps;

import com.opencsv.exceptions.CsvException;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static motorph_sytaxsippers_ps.OpenCsv_UpdateData.updateCSV;

public class AdminUserInterface_UpdateEmp extends javax.swing.JFrame {

    /**
     * Creates new form AdminUserInterface_UpdateEmp
     */
    public AdminUserInterface_UpdateEmp(String empNumber, String empLastName, String empFirstName, String empSSS, String empPhilH, String empTIN, String empPAGIBIG) {
        initComponents();

        //empNumber, empLastName, empFirstName,empSSS,empPhilH,empTIN,empPAGIBIG
        jText_EmpNumber.setText(empNumber);
        jText_LatName.setText(empLastName);
        jText_Fname.setText(empFirstName);
        jText_SSS.setText(empSSS);
        jText_PhilHealth.setText(empPhilH);
        jText_TIN.setText(empTIN);
        jText_PAGIBIG.setText(empPAGIBIG);

    }

    
            public void close() {

        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLbl_EmpNo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLbl_Fname = new javax.swing.JLabel();
        jLbl_SSSnum = new javax.swing.JLabel();
        jLbl_PhilHealth = new javax.swing.JLabel();
        jLbl_TIN = new javax.swing.JLabel();
        jLbl_PagIbig = new javax.swing.JLabel();
        jText_EmpNumber = new javax.swing.JTextField();
        jText_LatName = new javax.swing.JTextField();
        jText_Fname = new javax.swing.JTextField();
        jText_SSS = new javax.swing.JTextField();
        jText_PhilHealth = new javax.swing.JTextField();
        jText_TIN = new javax.swing.JTextField();
        jText_PAGIBIG = new javax.swing.JTextField();
        jBtn_Update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("UPDATE EMPLOYEE INFORMATION");

        jLbl_EmpNo.setText("EMPLOYEE NO:");

        jLabel4.setText("EMPLOYEE LAST NAME: ");

        jLbl_Fname.setText("EMPLOYEE FIRST NAME: ");

        jLbl_SSSnum.setText("SSS NUMBER:");

        jLbl_PhilHealth.setText("PHILHEALTH NUMBER:");

        jLbl_TIN.setText("TIN NUMBER:");

        jLbl_PagIbig.setText("PAGIBIG NUMBER:");

        jText_EmpNumber.setEditable(false);

        jBtn_Update.setText("UPDATE");
        jBtn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_UpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtn_Update)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbl_TIN, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLbl_PagIbig, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLbl_EmpNo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLbl_Fname, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLbl_SSSnum, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLbl_PhilHealth, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jText_SSS, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(jText_PhilHealth)
                            .addComponent(jText_TIN)
                            .addComponent(jText_PAGIBIG)
                            .addComponent(jText_EmpNumber)
                            .addComponent(jText_LatName)
                            .addComponent(jText_Fname)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel1)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_EmpNo)
                    .addComponent(jText_EmpNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_LatName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbl_Fname)
                    .addComponent(jText_Fname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_SSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbl_SSSnum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_PhilHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbl_PhilHealth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_TIN)
                    .addComponent(jText_TIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbl_PagIbig)
                    .addComponent(jText_PAGIBIG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBtn_Update)
                .addGap(9, 9, 9))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_UpdateActionPerformed

        String currentPath = System.getProperty("user.dir");
        String csvFile = currentPath + File.separator + "resources" + File.separator + "EmployeeDetails_AdminView.csv";

        String empNum = jText_EmpNumber.getText();
        String empLName = jText_LatName.getText();
        String empFName = jText_Fname.getText();
        String empSSSNo = jText_SSS.getText();
        String empPhilHNo = jText_PhilHealth.getText();
        String empTINNo = jText_TIN.getText();
        String empPAGIBIGNo = jText_PAGIBIG.getText();

        String empNumber = empNum; // Example employee number
        String[] updatedData = {empNum, empLName, empFName, empSSSNo, empPhilHNo, empTINNo, empPAGIBIGNo}; 
        
        try {
            updateCSV(csvFile, empNumber, updatedData);
            close();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (IllegalArgumentException e) {
            System.err.println(e.getMessage());
        } catch (CsvException ex) {
            Logger.getLogger(AdminUserInterface_UpdateEmp.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jBtn_UpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUserInterface_UpdateEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUserInterface_UpdateEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUserInterface_UpdateEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUserInterface_UpdateEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new AdminUserInterface_UpdateEmp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLbl_EmpNo;
    private javax.swing.JLabel jLbl_Fname;
    private javax.swing.JLabel jLbl_PagIbig;
    private javax.swing.JLabel jLbl_PhilHealth;
    private javax.swing.JLabel jLbl_SSSnum;
    private javax.swing.JLabel jLbl_TIN;
    private javax.swing.JTextField jText_EmpNumber;
    private javax.swing.JTextField jText_Fname;
    private javax.swing.JTextField jText_LatName;
    private javax.swing.JTextField jText_PAGIBIG;
    private javax.swing.JTextField jText_PhilHealth;
    private javax.swing.JTextField jText_SSS;
    private javax.swing.JTextField jText_TIN;
    // End of variables declaration//GEN-END:variables
}
